// Listener for messages from content script or popup
chrome.runtime.onMessage.addListener((request, sender, sendResponse) => {
  if (request.action === "processUserRequest") {
    console.log("Background: Received user request from content script:", request.prompt);

    chrome.storage.sync.get(['geminiApiKey', 'geminiModel'], (config) => {
      if (!config.geminiApiKey) {
        console.error("Background: Gemini API Key not configured.");
        sendResponse({ success: false, error: "Gemini API Key not configured." });
        return true; // Indicates asynchronous response
      }
      if (!config.geminiModel) {
        console.error("Background: Gemini Model not selected.");
        sendResponse({ success: false, error: "Gemini Model not selected." });
        return true; // Indicates asynchronous response
      }

      // Call the placeholder function to simulate Gemini API call
      callGeminiApi(config.geminiApiKey, config.geminiModel, request.prompt)
        .then(response => {
          sendResponse({ success: true, data: response });
        })
        .catch(error => {
          sendResponse({ success: false, error: error.message });
        });
    });
    return true; // Keep the message channel open for asynchronous response
  }
  // Add other message handlers if needed
});

// Placeholder function for Gemini API call
async function callGeminiApi(apiKey, model, prompt) {
  console.log(`Background: Calling Gemini API (placeholder) with Key: ${apiKey ? 'provided' : 'MISSING'}, Model: ${model}, Prompt: ${prompt}`);

  // Simulate API call delay
  await new Promise(resolve => setTimeout(resolve, 1000));

  // Simulate a Gemini response (e.g., a simple n8n node JSON)
  // In a real scenario, this would be a fetch request to the Gemini API
  // and would return the actual JSON for an n8n node or workflow.
  if (prompt.toLowerCase().includes("hello")) {
    return {
      message: "Placeholder: Hello from Gemini! This is a mock response.",
      n8nWorkflowData: {
        nodes: [
          {
            parameters: {
              value: "Hello World! This is a test node generated by Gemini (mock)."
            },
            name: "Sticky Note",
            type: "n8n-nodes-base.stickyNote",
            typeVersion: 1,
            position: [800, 600]
          }
        ],
        connections: {}
      }
    };
  } else {
    return {
      message: "Placeholder: Gemini received your prompt. This is a generic mock response.",
      n8nWorkflowData: {
        nodes: [
           {
            parameters: {
              value: `Received: ${prompt}. (Mock response)`
            },
            name: "Generated Note",
            type: "n8n-nodes-base.stickyNote",
            typeVersion: 1,
            position: [800, 600]
          }
        ],
        connections: {}
      }
    };
  }
}

chrome.runtime.onInstalled.addListener(() => {
  console.log("n8n Gemini Copilot extension installed.");
  // You can set default values here if needed
  // chrome.storage.sync.set({ geminiModel: 'gemini-pro' });
});

console.log("Background service worker started.");
