// n8n-gemini-copilot/background.js

chrome.runtime.onMessage.addListener((request, sender, sendResponse) => {
  if (request.action === "sendToGemini") {
    console.log("Background: Received 'sendToGemini' request", request);

    chrome.storage.sync.get(['geminiApiKey', 'geminiModel'], (config) => {
      if (chrome.runtime.lastError) {
        console.error("Background: Error retrieving config from storage:", chrome.runtime.lastError.message);
        sendResponse({ success: false, error: "Error retrieving settings from storage." });
        return true;
      }

      const { geminiApiKey, geminiModel } = config;

      if (!geminiApiKey) {
        console.error("Background: Gemini API Key not configured.");
        sendResponse({ success: false, error: "Gemini API Key is not configured. Please set it in the extension popup." });
        return true;
      }
      if (!geminiModel) {
        // Should ideally be set with a default in popup.js if not found
        console.error("Background: Gemini Model not selected.");
        sendResponse({ success: false, error: "Gemini Model is not selected. Please set it in the extension popup." });
        return true;
      }

      callGeminiApi(geminiApiKey, geminiModel, request.prompt)
        .then(response => sendResponse(response))
        .catch(error => {
          console.error("Background: Error in callGeminiApi:", error);
          sendResponse({ success: false, error: error.message || "An unknown error occurred during API call." });
        });
    });
    return true; // Indicates that the response will be sent asynchronously
  }
});

async function callGeminiApi(apiKey, model, prompt) {
  const apiUrl = `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${apiKey}`;
  console.log(`Background: Calling Gemini API. Model: ${model}, Prompt: "${prompt}"`);

  try {
    const response = await fetch(apiUrl, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        contents: [{
          parts: [{ text: prompt }],
        }],
      }),
    });

    if (!response.ok) {
      // Attempt to read error response from Gemini
      let errorData;
      try {
        errorData = await response.json();
      } catch (e) {
        // Ignore if error response is not JSON
      }
      console.error("Background: Gemini API request failed.", response.status, response.statusText, errorData);
      throw new Error(`Gemini API Error: ${response.status} ${response.statusText}. ${errorData?.error?.message || 'Check background console for details.'}`);
    }

    // TODO: Process actual Gemini response and send meaningful data to content script.
    // For now, we'll just log it and send a mock success.
    // const actualGeminiData = await response.json();
    // console.log("Background: Actual Gemini Response (raw):", actualGeminiData);
    // For example, to extract text: actualGeminiData.candidates[0].content.parts[0].text

    console.log("Background: Gemini API call placeholder successful (not processing actual response content yet).");
    return {
      success: true,
      message: "Placeholder: Gemini API call was successful (mock response).",
      data: {
        // This is where the processed n8n JSON would go
        originalPrompt: prompt,
        processedWorkflow: {
          nodes: [{
            parameters: { value: `Mock response for: ${prompt}` },
            name: "Generated by Gemini (Mock)",
            type: "n8n-nodes-base.stickyNote",
            typeVersion: 1,
            position: [Math.floor(Math.random() * 200 + 800), Math.floor(Math.random() * 200 + 600)]
          }],
          connections: {}
        }
      }
    };

  } catch (error) {
    console.error("Background: Fetch error calling Gemini API:", error);
    // Rethrow or return a structured error for sendResponse
    return { success: false, error: error.message || "Network error or API issue during Gemini call." };
  }
}

chrome.runtime.onInstalled.addListener(() => {
  console.log("n8n Gemini Copilot background script installed/updated.");
});
